user:
    prefix: user
    resource: 'Routing/user.yml'

bird:
    prefix: /bird
    resource: 'Routing/bird.yml'

observation:
    prefix: /observation
    resource: 'Routing/observation.yml'

star:
    prefix: /star
    resource: 'Routing/star.yml'

blog:
    prefix: /asso
    resource: 'Routing/blog.yml'

contact:
    prefix: /contact
    resource: Routing/contact.yml

association:
    prefix: /association
    resource: Routing/association.yml

homepage:
    path:     /
    defaults: { _controller: ObservationBundle:Default:index }
    methods: [GET]

faq_edit:
    path: /faq/edit/{page}
    defaults:
        _controller: ObservationBundle:Default:editFaq
    methods: [GET, POST]
faq:
    path: /faq
    defaults:
        _controller: ObservationBundle:Default:faq
    methods: [GET]


newsletter:
    prefix: /newsletter
    resource: Routing/newsletter.yml

picture:
    prefix: /picture
    resource: 'Routing/picture.yml'

user_export:
    path: /export-csv
    defaults:
      _controller: ObservationBundle:Export:export

landing_page:
    prefix: /landing
    resource: Routing/landing.yml