<?php

namespace ObservationBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use ObservationBundle\Entity\User;

/**
 * BirdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Fonction pour paginer la liste d'oiseaux
     */
    public function getPage($page, $numbers, $search = null, $type)
    {
        $query = $this->createQueryBuilder('b');
        if ($search !== null) {

            if ($type == 'bec') {
                $query
                    ->orWhere("b.bec LIKE :regex3")
                    ->setParameter('regex3', "%$search%");
            } else {
                $query
                    ->orWhere('b.lbNom LIKE :regex')
                    ->setParameter('regex', "%$search%")
                    ->orWhere("b.nomVern LIKE :regex2")
                    ->setParameter('regex2', "%$search%")
                    ->orWhere("b.plumage LIKE :regex4")
                    ->setParameter('regex4', "%$search%")
                    ->orWhere("b.couleur LIKE :regex5")
                    ->setParameter('regex5', "%$search%");
            }

        }
        $query->orderBy('b.nomVern', 'ASC')
            ->addOrderBy('b.lbNom', 'ASC')->getQuery();

        $query->setFirstResult(($page - 1) * $numbers)->setMaxResults($numbers);

        return new Paginator($query, true);
    }

    public function findForValidate(User $user)
    {
        $query = $this->createQueryBuilder('b')
            ->innerJoin('b.observations', 'o')
            ->where('o.user = :user')
            ->setParameter('user', $user)
            ->andWhere('o.validated = true');

        return $query->getQuery()->getResult();
    }
}
