<?php

namespace ObservationBundle\Repository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForCSV()
    {
        $query = $this->createQueryBuilder('f');

        return $query->getQuery()->getArrayResult();

    }
}
