<?php

namespace ObservationBundle\Repository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPictureGallery()
    {

        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->select('p.url')
            ->leftJoin('p.observation', 'obs')
            ->where('obs.validated = 1 ')
            ->orderBy('p.id', 'DESC')
            ->setMaxResults(4);

        return $query->getQuery()
            ->getResult();
    }




}
